resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: DockerCompose@0
  displayName: 'Run a Docker Compose command'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: 'Docker XL'

    dockerComposeCommand: 'up -d'


- task: AzureKeyVault@1
  displayName: 'Azure Key Vault: gitopsVault'
  inputs:
    azureSubscription: 'Free Trial (56c36adf-5db4-4dd8-9cdd-256b89a34bce)'

    KeyVaultName: gitopsVault

    SecretsFilter: testSecret


- script: |
   xlw apply -f xebialabs.yaml
  displayName: 'CMD Script'
  continueOnError: true
  env:
    XL_VALUE_RELEASE_NAME: $(testSecret)
    XL_VALUE_BUILD_NUMBER: $(Build.BuildId)


- task: DockerCompose@0
  displayName: 'Stop Docker Compose'
  inputs:
    containerregistrytype: 'Container Registry'

    dockerRegistryEndpoint: 'Docker XL'

    dockerComposeCommand: down
