### Creating home directories ##########################################################################################

apiVersion: xl-deploy/v1beta1
kind: Applications
spec:
- name: Applications/XL
  type: core.Directory

---

apiVersion: xl-deploy/v1beta1
kind: Infrastructure
spec:
- name: Infrastructure/XL
  type: core.Directory

---

apiVersion: xl-deploy/v1beta1
kind: Environments
spec:
- name: Environments/XL
  type: core.Directory

---

apiVersion: xl-deploy/v1beta1
kind: Configuration
spec:
- name: Configuration/XL
  type: core.Directory

---

########################################################################################################################

apiVersion: xl-deploy/v1beta1
metadata:
  Applications-home: Applications/XL
kind: Applications
spec:
- name: k8s
  type: core.Directory
  children:
    - name: rest-o-rant-api
      type: udm.Application
      children:
      - name: '1.0'
        type: udm.DeploymentPackage
        orchestrator:
          - parallel-by-container
          - sequential-by-deployed
        deployables:
          - name: rest-o-rant-api
            type: k8s.DeploymentSpec
            labels:
              io.kompose.service: rest-o-rant-api
            matchLabels:
              io.kompose.service: rest-o-rant-api
            deploymentName: rest-o-rant-api
            replicasCount: 1
            containers:
              - name: rest-o-rant-api
                type: k8s.ContainerSpec
                containerName: rest-o-rant-api
                image: xebialabsunsupported/rest-o-rant-api:v1
                ports:
                  - name: rest-o-rant-api-port-spec
                    type: k8s.ContainerPortSpec
                    containerPort: 8080

          - name: rest-o-rant-api-service
            type: k8s.ServiceSpec
            serviceName: rest-o-rant-api
            serviceType: LoadBalancer
            selectors:
              io.kompose.service: rest-o-rant-api
            ports:
              - name: port
                type: k8s.ServicePortSpec
                port: 8080
                targetPort: 8080

    - name: rest-o-rant-web
      type: udm.Application
      children:
        - name: '1.0'
          type: udm.DeploymentPackage
          applicationDependencies:
            rest-o-rant-api: "[1.0,1.0]"
          deployables:
            - name: rest-o-rant-web
              type: k8s.DeploymentSpec
              labels:
                io.kompose.service: rest-o-rant-web
              matchLabels:
                io.kompose.service: rest-o-rant-web
              deploymentName: rest-o-rant-web
              replicasCount: 1
              containers:
                - name: rest-o-rant-web
                  type: k8s.ContainerSpec
                  containerName: rest-o-rant-web
                  image: xebialabsunsupported/rest-o-rant-web:v1
                  ports:
                    - name: rest-o-rant-web-port-spec
                      type: k8s.ContainerPortSpec
                      containerPort: 80

            - name: rest-o-rant-web-service
              type: k8s.ServiceSpec
              serviceName: rest-o-rant-web
              serviceType: LoadBalancer
              selectors:
                io.kompose.service: rest-o-rant-web
              ports:
                - name: web
                  type: k8s.ServicePortSpec
                  port: 80
                  targetPort: 80

---
apiVersion: xl-deploy/v1beta1
metadata:
  Infrastructure-home: Infrastructure/XL
kind: Infrastructure
spec:
  - name: k8s
    type: core.Directory
    children:
      - name: localhost
        type: overthere.LocalHost
        os: UNIX
        children:
          - name: Mssql Client
            type: sql.MsSqlClient
            serverName: mySql
      - name: Minukube
        type: k8s.Master
        apiServerURL: https://192.168.99.100:8443
        skipTLS: true
        tlsCert: |
          -----BEGIN CERTIFICATE-----
          MIIDkjCCAnqgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
          a3ViZUNBMB4XDTE4MDcxMTA2MTI0NVoXDTE5MDcxMjA2MTI0NVowLDEXMBUGA1UE
          ChMOc3lzdGVtOm1hc3RlcnMxETAPBgNVBAMTCG1pbmlrdWJlMIIBIjANBgkqhkiG
          9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5jp4CBam+W7Wh8+y5Uxwqkmm0rBcqONhCxwX
          g6mzdmxdSCgEstOLztIKLy80PSPWdrvt5nMoIMP3Qg28P6+7WMePWGQPn5rtK4ws
          6wZcseMRZj/zDYiR+2UBQsQg0z6qkYilQQHd5gUKfsYhwpr/i3Dmgux1xGniMUuQ
          BW2epKpgViOKTaWqEuPt3Gr2z0323YKcSv20ibh/zHHoELe1aK6CrzX4V518k4EZ
          JfVCPA3SCM4L+qErYecyeTeJ+gG2bDTdW9uWJDJW+xgnu7QOcEXxE2rU35Tsput1
          pVXINIuo7jIw1oEN7PxEUCobiklJAwTDskFkmrvxUYrX6O9pxQIDAQABo4HVMIHS
          MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
          DAYDVR0TAQH/BAIwADCBkgYDVR0RBIGKMIGHggptaW5pa3ViZUNBgiRrdWJlcm5l
          dGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWyCFmt1YmVybmV0ZXMuZGVmYXVs
          dC5zdmOCEmt1YmVybmV0ZXMuZGVmYXVsdIIKa3ViZXJuZXRlc4IJbG9jYWxob3N0
          hwTAqGNkhwQKYAABhwQKAAABMA0GCSqGSIb3DQEBCwUAA4IBAQCe56t/b2j4OnxL
          wpr9ow0ip4g1dG8SFghdDCEpenhbBuyqBPLSTn4U5ce81j9+HbPmcj+pE5SIaSrU
          WbP22d7X1RMsgdwAhqC3wslfaFJneE5s2OKV4R9bx+VXOyb9HTU83ZzuB1z/i/uT
          eQI6Jv5HW77ynwJqscfJFnU20DUw9MTRMFocoqjrGfzK5HFAiqj8gRPaNRqdNWh+
          1rv5jf+7pHNRUUPuv5oFR3GAz83BtQov3z0BX1I001UpFydPd6+uJl7PkBMy4ORs
          zK5LlildXN9QtfCnlPkqRqtYELCzo45nPvzin9VXDKrUhofrEvIzvQMy67trw5WJ
          ITdNhW6T
          -----END CERTIFICATE-----
        tlsPrivateKey: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEA5jp4CBam+W7Wh8+y5Uxwqkmm0rBcqONhCxwXg6mzdmxdSCgE
          stOLztIKLy80PSPWdrvt5nMoIMP3Qg28P6+7WMePWGQPn5rtK4ws6wZcseMRZj/z
          DYiR+2UBQsQg0z6qkYilQQHd5gUKfsYhwpr/i3Dmgux1xGniMUuQBW2epKpgViOK
          TaWqEuPt3Gr2z0323YKcSv20ibh/zHHoELe1aK6CrzX4V518k4EZJfVCPA3SCM4L
          +qErYecyeTeJ+gG2bDTdW9uWJDJW+xgnu7QOcEXxE2rU35Tsput1pVXINIuo7jIw
          1oEN7PxEUCobiklJAwTDskFkmrvxUYrX6O9pxQIDAQABAoIBAH+5VDn4hy2+Jdo2
          ieLX43E1Zw1ftigj7QSC0zDCBsPeHmoXeXPUFK3qrKe8oliA90vrunGs1UhIL3Y/
          tH4IegEoxQeei2RaSNVt8MV6RBaUCGUXeTm62HIFeQuXTzaif3I5wqQr6vTfOxFV
          zgjugHLVcayUjkknDMuYRhAc3nQu292cy3+/x2AKfmsOhsorRjruJ3icmEki5YTr
          meRrGYVAvFB51c3DWncI1p+avzAJ6+KTNXSj06OzBNJ859Rsg0vWwfvHmNWnzf2H
          JaiFh22YLOzi/HLik5kwWCDwyLFUsUBfKbzcsmqashjVfbIV66k2c+y4QethOWsu
          fSxHbUECgYEA9PkR7sdGytT8JhWjb3dCqwrU676jL33i3gJJkRRjUr8s6avirYOb
          NZTA1YUJ01ZZofzMhcmdiVjCGcgJSNSboRfqeVb0SFCvGWyGeVDOPLuhB9Ysz9fK
          6UGwN6nwOEO1WwReR/1UqjHZUrfYhZOtNJ9BrzDkmTvUOOBlBNJdx4kCgYEA8Jd9
          uQJXVIT+QJc3nB/T3auyP9tz51BHmC/Z6Q9cnB1t0Lasy/NVZyDAFWEsjsYYe0U6
          bhkQwW2hd3RgMAp8PI9LZ+bs7rwIfRJ/PUidA77tTc6DwmFfa/xG/dCGLd8j4QW/
          9E+hMTkfOJnFpb0EKbAkmvQovf7FqgTbPinmRV0CgYBrCSTPutxwpWziyxOVEXvc
          tifgNXShvJRSwpcYP9tB/WwHUWYCwH0hhTRYVv+7CoCxaX6HeldN+q0cjK2Z1+OE
          GKoHiHnF2xMWvbdn7GmgWa77eJYt3jC3iE8Rkzv1qYflE9yKAeNrVcqJ/PArNSI5
          2tfdTzSiy2Rn0Yvx9mSpWQKBgEEEv64y6sTlmAx+kUG4/Dmov+gv91eow2Bmdh5c
          z2tFLLs90t7fKNJQ8HgWpcMD1/PgVpUQYw3TAdLVeXUiMEbxdrBioN83o5ehWw+F
          wyETBPCFAeiTBgWZzNmk884Lwpd6RVDSAD7cMArMy7Qpq6lUd+AEYcpOwr5ax6E6
          E4flAoGBAI35ASZgUpPpgKReUPNOsYhw63HKmzcJURF9XX8Y78IGIJaEonV9XU0v
          scx0yVdL2yRRttlAlTu0/XiRGAWN3LLhkp0TKOese+3SlVS2zaU4U5o+odNnHbIJ
          k+23dHabNapL/LiqyV1z6xO3ZhL6OcjxUNU4DtHygi0IWurp43eD
          -----END RSA PRIVATE KEY-----
        children:
          - name: default
            type: k8s.Namespace
            namespaceName: default
---
apiVersion: xl-deploy/v1beta1
metadata:
  Configuration-home: Configuration/XL
kind: Configuration
spec:
- name: smtpServer
  type: mail.SmtpServer
  host: localhost
  fromAddress: noreply@xebialabs.com

- name: emailNotification
  type: trigger.EmailNotification
  toAddresses:
  - admin@xebialabs.com
  subject: hello
  body: test
  mailServer: ~Configuration/smtpServer

---
apiVersion: xl-deploy/v1beta1
metadata:
  Configuration-home: Configuration/XL
kind: Configuration
spec:
- name: t1
  type: trigger.TaskTrigger
  toState: DONE
  actions:
    - Configuration/XL/emailNotification

---
apiVersion: xl-deploy/v1beta1
kind: Configuration
spec:
- name: Configuration/XL/t2
  type: trigger.TaskTrigger
  toState: DONE
  actions:
    - Configuration/XL/emailNotification

---
apiVersion: xl-deploy/v1beta1
kind: Environments
metadata:
  Environments-home: Environments/XL
  Configuration-home: Configuration/XL
  Infrastructure-home: Infrastructure/XL
spec:
  - name: k8s
    type: core.Directory
    children:
      - name: Local
        type: udm.Environment
        triggers:
          - ~Configuration/t1
          - Configuration/XL/t2
        members:
          - ~Infrastructure/k8s/Minukube/default
        dictionaries:
          - ../../dict2
  - name: dict
    type: udm.Dictionary
    entries:
      user: admin
      password: qwerty
    encryptedEntries:
      user: admin
      password: qwerty
  - name: dict2
    type: udm.Dictionary

#### Docker setup ######################################################################################################

---

apiVersion: xl-deploy/v1beta1
metadata:
  Applications-home: Applications/XL
kind: Applications
spec:
- name: docker
  type: core.Directory
  children:
    - name: Rest-o-Rant Api
      type: udm.Application
      children:
      - name: '1.0'
        type: udm.DeploymentPackage
        deployables:
          - name: rest-o-rant-network
            type: docker.NetworkSpec
            networkName: rest-o-rant
            driver: bridge
          - name: rest-o-rant-api
            type: docker.ContainerSpec
            image: xebialabsunsupported/rest-o-rant-api
            networks:
            - rest-o-rant
            showLogsAfter: 5
    - name: Rest-o-Rant Web
      type: udm.Application
      children:
      - name: '1.0'
        type: udm.DeploymentPackage
        deployables:
          - name: rest-o-rant-web
            type: docker.ContainerSpec
            image: xebialabsunsupported/rest-o-rant-web
            networks:
            - rest-o-rant
            showLogsAfter: 5
            portBindings:
            - name: ports
              type: docker.PortSpec
              hostPort: 8080
              containerPort: 80
              protocol: tcp


---
apiVersion: xl-deploy/v1beta1
metadata:
  Infrastructure-home: Infrastructure/XL
kind: Infrastructure
spec:
  - name: docker
    type: core.Directory
    children:
      - name: dockerHost
        type: docker.Engine
        dockerHost: http://dockerproxy:2375

---
apiVersion: xl-deploy/v1beta1
kind: Environments
metadata:
  Environments-home: Environments/XL
  Infrastructure-home: Infrastructure/XL
spec:
  - name: docker
    type: core.Directory
    children:
      - name: dockerEnv
        type: udm.Environment
        members:
          - ~Infrastructure/docker/dockerHost

---
apiVersion: xl-deploy/v1beta1
metadata:
  Applications-home: Applications/XL
kind: Applications
spec:
  - name: files
    type: core.Directory
    children:
    - name: FilesAndFoldersTest
      type: udm.Application
      children:
      - name: '1.0'
        type: udm.DeploymentPackage
        deployables:
          - name: myfile
            type: file.File
            file: !file files/test1.txt
            targetPath: "!test test"
          - name: myfile2
            type: file.File
            file: !file files/test/test2.txt
          - name: myfolder
            type: file.Folder
            file: !file folder
